name: sparkle_lite
description: Sparkle Lite — Women & Family Health Companion App
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  provider: ^6.1.5+1
  uuid: ^4.5.3
  smart_date_formatter: ^2.3.0
  file_picker: ^11.0.2
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  intl: ^0.20.3
  dio: ^5.10.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^4.1.1
  firebase_auth_mocks: ^0.15.2
  firebase_core_platform_interface: ^7.1.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.3.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google_logo.svg

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: assets/icons/sparkle_icon.png
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: assets/icons/sparkle_icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: '#2E7D8C'
  image: assets/icons/sparkle_icon.png
  color_dark: '#1A5F6E'
  image_dark: assets/icons/sparkle_icon.png
  android_12:
    color: '#2E7D8C'
    image: assets/icons/sparkle_icon.png
    icon_background_color: '#2E7D8C'
  web: false