// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJsUFAKGnf-_zK4CO75ffogsy8J1JwMw',
    appId: '1:467242628130:web:24186e5510a082c94c867b',
    messagingSenderId: '467242628130',
    projectId: 'sparkle-lite-523e6',
    authDomain: 'sparkle-lite-523e6.firebaseapp.com',
    storageBucket: 'sparkle-lite-523e6.firebasestorage.app',
    measurementId: 'G-G34KWFHGHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiuIm6DA-yDiU7XfSoddeaiDgqQ_e7YiA',
    appId: '1:467242628130:android:b70aa12a3a0fc8504c867b',
    messagingSenderId: '467242628130',
    projectId: 'sparkle-lite-523e6',
    storageBucket: 'sparkle-lite-523e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmB9ZkXWUYhuRNVmlC_AXOa5YjdZdOXLI',
    appId: '1:467242628130:ios:2f1fc79b7dd648ad4c867b',
    messagingSenderId: '467242628130',
    projectId: 'sparkle-lite-523e6',
    storageBucket: 'sparkle-lite-523e6.firebasestorage.app',
    iosBundleId: 'com.example.sparkleLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmB9ZkXWUYhuRNVmlC_AXOa5YjdZdOXLI',
    appId: '1:467242628130:ios:2f1fc79b7dd648ad4c867b',
    messagingSenderId: '467242628130',
    projectId: 'sparkle-lite-523e6',
    storageBucket: 'sparkle-lite-523e6.firebasestorage.app',
    iosBundleId: 'com.example.sparkleLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByJsUFAKGnf-_zK4CO75ffogsy8J1JwMw',
    appId: '1:467242628130:web:a5efdb8b99822eee4c867b',
    messagingSenderId: '467242628130',
    projectId: 'sparkle-lite-523e6',
    authDomain: 'sparkle-lite-523e6.firebaseapp.com',
    storageBucket: 'sparkle-lite-523e6.firebasestorage.app',
    measurementId: 'G-Q3MF4NQYDP',
  );
}
